### ISSUE TITLE
AvaloniaRibbon on Avalonia 11.0.0

### ISSUE THREAD

**Issue by slovakfreelancer** [Splitwirez/AvaloniaRibbon#35]
Perfect work!
It is possible that you upgrade this project to use Avalonia 11.0.0? There is Avalonia 11.0.0-preview4 already. I want to use it with docking on Avalonia 11. I had tried myself but I was not successful due to errors:

**Error	XAMLIL	Unable to find suitable setter or adder for property FontSize of type Avalonia.Controls:Avalonia.Controls.TextBlock for argument netstandard:System.String**

**Error	XAMLIL	Unable to find suitable setter or adder for property FontWeight of type Avalonia.Controls:Avalonia.Controls.TextBlock for argument netstandard:System.String**

**Error	XAMLIL	Internal compiler error while transforming node XamlX.Ast.XamlAstObjectNode:
XamlX.XamlTypeSystemException: Content (or substitute) attribute is declared on multiple properties of AvaloniaUI.Ribbon:AvaloniaUI.Ribbon.RibbonTab
   at XamlX.Transform.TransformerConfiguration.FindContentProperty(IXamlType type)
   at XamlX.Transform.Transformers.ResolveContentPropertyTransformer.Transform(AstTransformationContext context, IXamlAstNode node)
   at XamlX.Transform.AstTransformationContext.Visitor.Visit(IXamlAstNode node) Line 300, position 18.	MainWindow.axaml**

Thank you!

**Comment by tingspain** [comment]
Any update on this issue? THANKS!!!
